name: Deploy FastAPI

on:
  push:
    branches:
      - master

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - uses: google-github-actions/setup-gcloud@v2

    - run: |
        gcloud auth configure-docker asia-south2-docker.pkg.dev

    - run: |
        docker build -t asia-south2-docker.pkg.dev/project-c2ff729b-747d-4105-b87/fastapi-images/fastapi-app:latest .

    - run: |
        docker push asia-south2-docker.pkg.dev/project-c2ff729b-747d-4105-b87/fastapi-images/fastapi-app:latest

    - name: Get access token
      id: gcp_token
      run: echo "token=$(gcloud auth print-access-token)" >> "$GITHUB_OUTPUT"

    - name: SSH Deploy
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        envs: GCP_TOKEN
        script: |
          docker login -u oauth2accesstoken -p "$GCP_TOKEN" https://asia-south2-docker.pkg.dev

          docker pull asia-south2-docker.pkg.dev/project-c2ff729b-747d-4105-b87/fastapi-images/fastapi-app:latest

          docker stop fastapi || true
          docker rm fastapi || true

          docker run -d \
             --name fastapi \
             -p 80:8000 \
             -e DB_HOST="${{ secrets.DB_HOST }}" \
             -e DB_USER="${{ secrets.DB_USER }}" \
             -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
             -e DB_NAME="${{ secrets.DB_NAME }}" \
             -e DB_PORT="${{ secrets.DB_PORT }}" \
             -e CELERY_BROKER_URL="${{ secrets.CELERY_BROKER_URL }}" \
             asia-south2-docker.pkg.dev/project-c2ff729b-747d-4105-b87/fastapi-images/fastapi-app:latest
      env:
        GCP_TOKEN: ${{ steps.gcp_token.outputs.token }}